#!/usr/bin/env bash

# shellcheck disable=SC2155

set -Eeuo pipefail

source "$(dirname "$0")"/Commons/common.sh

#################
#   CONSTANTS   #
#################

readonly SCRIPT_ABS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"

readonly SWIFT_BUILD_DIR_NAME=".build"

readonly COVERAGE_DIR_NAME=".coverage"
readonly COVERAGE_INCLUDE_LIST=(
        "Sources/ConfidentialCore/"
        "Sources/ConfidentialKit/"
    )

#################
#   FUNCTIONS   #
#################

function set_up() {
    echo "---------------------------- SET UP ----------------------------"
    echo "🍳"

    echo "Cleaning up SPM build artifacts"
    swift package clean

    echo "-------------------------- END SET UP --------------------------"
}

function clean_up() {
    echo "--------------------------- CLEAN UP ---------------------------"
    echo "🧽"

    # SPM .build directory generated by SPM interferes with 
    # Xcode build system, so it needs to be removed once script execution is done.
    local -r swift_build_dir_path="$SCRIPT_ABS_PATH/../$SWIFT_BUILD_DIR_NAME"
    if [[ -d "$swift_build_dir_path" ]]
    then
        echo "Deleting SPM $SWIFT_BUILD_DIR_NAME directory"
        rm -rf "$swift_build_dir_path"
    fi

    echo "------------------------- END CLEAN UP -------------------------"
}

function swift_test() {
    echo "-------------------------- SWIFT TEST --------------------------"
    echo "🧪"

    swift test --parallel --enable-code-coverage

    echo "------------------------ END SWIFT TEST ------------------------"
}

function swift_package_name() {
    swift package describe | awk '/Name:/ { print $2; exit; }'
}

function export_coverage_data() {
    echo "------------------------ COVERAGE DATA -------------------------"

    echo_progress "Exporting code coverage data"

    local -r package_name=$(swift_package_name)
    local -r bin_path="$SWIFT_BUILD_DIR_NAME/debug/${package_name}PackageTests.xctest/Contents/MacOS/${package_name}PackageTests"
    local -r profdata_path="$SWIFT_BUILD_DIR_NAME/debug/codecov/default.profdata"
    local -r coverage_report_path="$COVERAGE_DIR_NAME/$package_name.lcov"

    pushd_quiet "$SCRIPT_ABS_PATH/.."
    mkdir -p "$COVERAGE_DIR_NAME"
    # shellcheck disable=SC2068
    xcrun llvm-cov export -format="lcov" "$bin_path" -instr-profile "$profdata_path" ${COVERAGE_INCLUDE_LIST[@]} \
        > "$coverage_report_path"
    echo "Code coverage report: $(pwd -P)/$coverage_report_path"
    popd_quiet

    echo "---------------------- END COVERAGE DATA -----------------------"
}

###################
#   ENTRY POINT   #
###################

trap clean_up EXIT

set_up

swift_test
export_coverage_data
